### PR TITLE
support PHP Enums

### PR DESCRIPTION
**Pull request by patrocle**
support PHP Enums hasn't been merged

### CODE REVIEW

**Comment by jpkleemans** [comment]
Hi, thanks for your PR! Sorry for my late reply.
Could you add a unit test that illustrates the problem, so the unit test shows that your code fixes that problem?

**Comment by patrocle** [comment]
Hi, I update the test it_works_with_enumerated_casts to show that when we update an enum attribute that doesn't have an event match with $value->name === $expected, it try to cast to (string) $value === $expected
Thanks

**Comment by obrunsmann** [comment]
Any chance to get this merged? Solved exception on my side perfectly fine - thanks @patrocle

**Comment by obrunsmann** [comment]
@jpkleemans ? 🥴🥴

**Comment by patrocle** [comment]
@jpkleemans Hi, can you merge this ? Thanks

**Comment by jpkleemans** [comment]
@patrocle thanks for adding the test. But it looks like it fails?

image

Could you have a look at it?

**Comment by jpkleemans** [comment]
Fixed in https://github.com/jpkleemans/attribute-events/pull/18

**Pull request closed without merging**
